# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI - Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: ${{matrix.browser}} - node ${{ matrix.node }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        node: [16]
        os: [ubuntu-latest, windows-latest]
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - if: ${{ matrix.browser == 'chrome' }}
        name: Check chromedriver version
        run: chromedriver --version
      - if: ${{ matrix.browser == 'firefox' }}
        name: Check geckodriver version
        run: geckodriver --version
      - name: Run test on ${{ matrix.browser }}
        run: npm run test:${{ matrix.browser }}
      - name: Upload artifact to reports/
        uses: actions/upload-artifact@v3
        with:
          path: reports/
